### ISSUE TITLE
Consider accepting non-accessibility contributions?

### ISSUE THREAD

**Issue by JeanSebTr** [Accessible360/accessible-slick#29]
I was about to make a PR but noticed you're only accepting accessibility contributions. Slick has been inactive for 2 years now and have a lot of issues and PR waiting open. Your repo have a working build, is active and by being accessible can be considered superior quality. I understand this would mean more work, but would you consider accepting non-accessibility related contributions?

**Comment by jasonwebb** [comment]
Hey Jean-Sébastien! It's a good question for sure. This package and repo are provided by [Accessible360](https://accessible360.com/) to help "stop the bleeding" around accessibility caused by Slick Slider downstream, but not treat all of the other conditions that it currently has outside of accessibility.

Since our company is focused on digital accessibility and is pretty small and lean, we just wouldn't have the capacity or skillset to support such a large community outside of our core business. Currently Slick Slider has over 1,000 open issues and over 200 open PRs, some going back several years - that's quite a lift for any organization!

I agree that it appears the Slick Slider project has been abandoned for quite while now, but because it has not been officially deprecated/archived, people are still using it without knowing that it isn't a good idea. I would suggest trying to directly reach out to the project's author to ask them to add a deprecation notice to Github and NPM, or archive it entirely, or maybe even transfer it to a "successor" (org or maintainer). There is also some discussion going on around adding a feature to "claim" abandoned repos, which you could upvote and/or participate in: https://github.com/isaacs/github/issues/1385. Beyond that, maybe you could help get the word out about the status of this repo by writing a short article or posting on social media, which could potentially be found in search results when people are researching Slick in the future!
