### ISSUE TITLE
Links within slide content

### ISSUE THREAD

**Issue by mattpaz** [Accessible360/accessible-slick#36]
If a slide contains a link, should it be navigable by keyboard?

**Comment by jasonwebb** [comment]
Hi @mattpaz! Slide navigation (like slide dots and prev/next buttons) are generally expected by users to work independently from whatever content is found in the individual slides. The reasoning for why direct keyboard navigation (using the `Left` and `Right` arrow keys) has been removed can be found in #15.

If I'm misinterpreting your question, please let me know!

**Comment by mattpaz** [comment]
Thanks for the response!  Indeed, I wasn't talking about navigation between slides, but rather, a link within a slide.  So, instead of a simple image, I've got HTML/markup inside each slide.

For instance, take the example below ... 
![image](https://user-images.githubusercontent.com/854153/125087913-ebc3df80-e09a-11eb-9511-30c2f3869cde.png)

The button there is an actual link.  Wasn't sure if one should expect to be able to tab down to the link after switching to a slide.  Does that help clarify my question?

**Comment by jasonwebb** [comment]
[WCAG 2.4.3](https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html), and maybe [WCAG 1.3.2](https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence.html) too, talks about how the tab sequence of content, and content in general, on a page should be "logical", but is a bit fuzzy about what that exactly means. Most of the time, content should be navigable from left-to-right, top-to-bottom, the way you'd read content visually on a page. You might be able to argue that other sequences are "logical" in different situations, but if you stick to the natural reading order you're pretty much never wrong.

In this use case the natural reading order, and therefore the most logical tab sequence (IMHO) could either be:

1. Previous button, "This is a link/href" link, Next button, each slide dot bottom (left to right), OR
2. Previous button, "This is a link/href" link, each slide dot button (left to right), Next button.

But if other slides contain a focusable element that is visually placed to the right of the slide dots, that second option above probably wouldn't make sense anymore. So I would say that the first option is the smartest in general when you can't predict the inner content of each slide, which is why that is the default tab sequence for accessible-slick! 

Finally, keyboard and screen reader users expect that the structure of content on a page doesn't change much, if at all, as they are interact with it. If the slide content can be found between the Previous and Next buttons the first time they skim the page, then they would expect to be able to find other slide content there to whenever they use a control to change the active slide.

Hope that helps!

**Comment by mattpaz** [comment]
Well, I guess that's food for thought, but still uncertain about what should be expected.  I'll go ahead and close this for now, but will circle back and add additional findings should any eureka moments emerge.  Thanks for responding.

**Comment by jasonwebb** [comment]
Sorry about that! Keyboard and screen reader users would expect to navigate the content from left-to-right, top-to-bottom as it is shown visually. Then when you activate any of the controls, they would then expect to navigate back to the slide content on their own. The sequence of the content should stay the same, and the user would expect to be able to navigate through it on their own.

**Comment by mattpaz** [comment]
Ah, 10-4.  Sounds like I shouldn't expect the user to want to navigate to the link inside the slide by tabbing to it.  Thanks for clarifying that.
